### ISSUE TITLE
OSX config 

### ISSUE THREAD

**Issue by JoshuaAdrianJones** [lubien/bookmarker#12]
This little script is great but I had to change the config file path to the correct location the bookmarks are stored on OSX / mac. 

It might be useful to add this detail in the readme

for mac the location was ~/Library/Application Support/Google/Chrome/Default/Bookmarks
and I had to rebuild the escript after making the config file edit for it to work.

**Comment by lubien** [comment]
Thanks for the insight. That was the reason I left the flag `-f` available.

```
Usage: bookmarker [options]

  -f, --file            Set where your chrome bookmarks file is.
			Default: ~/.config/google-chrome/Default/Bookmarks
```

But it would be great if this script checked the presence of both paths. 

Wanna give a try?

**Comment by ramkumarr** [comment]
#13
