### ISSUE TITLE
Usage is not clear from Readme

### ISSUE THREAD

**Issue by VeraCologne** [lubien/bookmarker#17]
Found this project through Hacktoberfest and would like to contribute, but it took me a while to figure out how to run this. I have never seen an escript application before, so this might be completely obvious to anyone else, but it might be nice to add this to the usage section of the readme.

**Comment by VeraCologne** [comment]
I'm still not sure if I understood escript correctly, but I have been able to run bookmarker by typing `escript bookmarker` in my shell. So for me, Usage should be "escript bookmarker [options]" instead of just "bookmarker options".

**Comment by lubien** [comment]
Just did a quick clone here. Here's my routine:

```sh
~/dev λ clone git@github.com:lubien/bookmarker.git
Cloning into 'bookmarker'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 216 (delta 15), reused 27 (delta 10), pack-reused 176
Receiving objects: 100% (216/216), 30.04 KiB | 168.00 KiB/s, done.
Resolving deltas: 100% (100/100), done.

~/dev/bookmarker λ mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  poison 4.0.1
* Getting poison (Hex package)

~/dev/bookmarker λ mix escript.build
==> poison
Compiling 4 files (.ex)
Generated poison app
==> bookmarker
Compiling 5 files (.ex)
Generated bookmarker app
Generated escript bookmarker with MIX_ENV=dev
    
~/dev/bookmarker λ ./bookmarker 
bookmarker   config/      .git/        lib/         mix.exs      README.md    .travis.yml  
_build/      deps/        .gitignore   LICENSE.md   mix.lock     test/        

~/dev/bookmarker λ ./bookmarker --help
Usage: bookmarker [options]
```

To use it the first step would be the build then running it on the shell. And as @mracos there' an option to install directly from GitHub now on the README without cloning so I think `bookmarker [options]` suits best my interest.

**Comment by VeraCologne** [comment]
Oh ok, I get it now.
