### ISSUE TITLE
Is there it for Firefox?

### ISSUE THREAD

**Issue by alexandre-mbm** [lubien/bookmarker#7]
Olá! Não leve a mal a pergunta. Acabo de ver que você pode falar português. Estou procurando solução semelhante também para Firefox. Uso os dois navegadores.

Preciso colher pastas de favoritos temporários (pesquisas) como listas Markdown. Por enquanto estou usando um shell script que faz isso a partir de um colagem de links.

**Comment by lubien** [comment]
Não cheguei a pesquisar para firefox.

**Comment by alexandre-mbm** [comment]
Acho que vou forkar. Conhecer a Elixir. Uma funcionalidade que preciso é exportar apenas uma pasta.

**Comment by lubien** [comment]
É um bom projeto pra iniciar na linguagem (foi justamente isso que eu fiz).

Em ter, 2 de mai de 2017 18:57, Alexandre Magno <notifications@github.com>
escreveu:

**Comment by alexandre-mbm** [comment]
```
~/.mozilla/firefox/PROFILE/places.sqlite
~/.mozilla/firefox/PROFILE/bookmarkbackups/bookmarks-ID.jsonlz4
```
Mas talvez eu não tenha tempo pra isso.

**Comment by alexandre-mbm** [comment]
I already solved my problem: [treclip](/alexandre-mbm/treclip)
